export const stations: string[] = [
  "Tucson, AZ",
  "Phoenix, AZ",
  "Mesa, AZ",
  "San Diego, CA",
  "Los Angeles, CA",
  "Long Beach, CA",
  "Oakland, CA",
  "Sacramento, CA",
  "San Francisco, CA",
  "San Jose, CA",
  "Denver, CO",
  "Colorado Springs, CO",
  "Washington, DC",
  "Jacksonville, FL",
  "Miami, FL",
  "Tampa, FL",
  "Atlanta, GA",
  "Honolulu, HI",
  "Des Moines, IA",
  "Boise, ID",
  "Chicago, IL",
  "Indianapolis, IN",
  "Louisville, KY",
  "New Orleans, LA",
  "Boston, MA",
  "Baltimore, MD",
  "Detroit, MI",
  "Minneapolis, MN",
  "Kansas City, MO",
  "St. Louis, MO",
  "Charlotte, NC",
  "Raleigh, NC",
  "Omaha, NE",
  "Albuquerque, NM",
  "Las Vegas, NV",
  "New York City, NY",
  "Buffalo, NY",
  "Rochester, NY",
  "Columbus, OH",
  "Cincinnati, OH",
  "Cleveland, OH",
  "Portland, OR",
  "Philadelphia, PA",
  "Pittsburgh, PA",
  "Memphis, TN",
  "Nashville, TN",
  "Austin, TX",
  "Dallas, TX",
  "Fort Worth, TX",
  "Houston, TX",
  "San Antonio, TX",
  "El Paso, TX",
  "Arlington, TX",
  "Salt Lake City, UT",
  "Virginia Beach, VA",
  "Seattle, WA",
  "Milwaukee, WI"
];
